//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Web.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class MH_HDMH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MH_HDMH()
        {
            this.MH_CT_HDMH = new HashSet<MH_CT_HDMH>();
            this.MH_CT_HDMDV = new HashSet<MH_CT_HDMDV>();
        }
    
        public string SO_HD { get; set; }
        public System.DateTime NGAY_HD { get; set; }
        public string KY_HIEU_HD { get; set; }
        public string MAU_SO_HD { get; set; }
        public string MA_NCC { get; set; }
        public string THAM_CHIEU { get; set; }
        public string TRUC_THUOC { get; set; }
        public decimal TONG_TIEN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MH_CT_HDMH> MH_CT_HDMH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MH_CT_HDMDV> MH_CT_HDMDV { get; set; }
        public virtual NCC NCC { get; set; }
    }
}
