//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Web.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class MH_HDMDV
    {
        public string SO_HD { get; set; }
        public System.DateTime NGAY_HD { get; set; }
        public string KY_HIEU_HD { get; set; }
        public string MAU_SO_HD { get; set; }
        public string MA_NCC { get; set; }
        public string TRUC_THUOC { get; set; }
        public decimal TONG_TIEN { get; set; }
    
        public virtual CCTC_CONG_TY CCTC_CONG_TY { get; set; }
        public virtual NCC NCC { get; set; }
    }
}
