//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Web.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class NCC_LIEN_HE
    {
        public int ID_LIEN_HE { get; set; }
        public string MA_NHA_CUNG_CAP { get; set; }
        public string NGUOI_LIEN_HE { get; set; }
        public string CHUC_VU { get; set; }
        public Nullable<System.DateTime> NGAY_SINH { get; set; }
        public string GIOI_TINH { get; set; }
        public string SDT { get; set; }
        public string EMAIL { get; set; }
        public string SKYPE { get; set; }
        public string FACEBOOK { get; set; }
        public string GHI_CHU { get; set; }
    
        public virtual NCC NCC { get; set; }
    }
}
